### PR TITLE
Broadcast notify on Buffer.Close

### LINKED ISSUE #298: Potential regression in v2.2.5, indefinitely stuck `packetio.(*Buffer).Read`
There seems to be a regression starting from commit https://github.com/pion/transport/commit/c72ccc10e2c6eb585dcacc6088631d5c4e6d0f1e

Calls to `packetio.(*Buffer).Read` are at times stuck indefinitely, even past closing the connection.

```
goroutine 63548 [select, 1565 minutes]:
github.com/pion/transport/v2/packetio.(*Buffer).Read(0x40006c0ba0, {0x4000ed2000, 0x5b4, 0x5b4})
	github.com/pion/transport/v2@v2.2.5/packetio/buffer.go:265 +0x1b4
github.com/pion/srtp/v2.(*ReadStreamSRTP).Read(...)
	github.com/pion/srtp/v2@v2.0.18/stream_srtp.go:79
github.com/pion/webrtc/v3.(*DTLSTransport).streamsForSSRC.func1({0x4000ed2000?, 0x5?, 0x2?}, 0x4000dcc420?)
	github.com/pion/webrtc/v3@v3.2.40/dtlstransport.go:494 +0x54
github.com/pion/interceptor.RTPReaderFunc.Read(0x40004cf9b0?, {0x4000ed2000?, 0x2?, 0x2?}, 0x9603c8?)
	github.com/pion/interceptor@v0.1.29/interceptor.go:91 +0x38
github.com/pion/interceptor/pkg/report.(*ReceiverInterceptor).BindRemoteStream.func1({0x4000ed2000, 0x28708?, 0x5b4}, 0x2838c?)
	github.com/pion/interceptor@v0.1.29/pkg/report/receiver_interceptor.go:126 +0x54
github.com/pion/interceptor.RTPReaderFunc.Read(0x0?, {0x4000ed2000?, 0x4001bc25e8?, 0x188c0?}, 0x2000?)
	github.com/pion/interceptor@v0.1.29/interceptor.go:91 +0x38
github.com/pion/interceptor/pkg/twcc.(*SenderInterceptor).BindRemoteStream.func1({0x4000ed2000, 0x0?, 0x5b4}, 0x4001bc2680?)
	github.com/pion/interceptor@v0.1.29/pkg/twcc/sender_interceptor.go:119 +0x60
github.com/pion/interceptor.RTPReaderFunc.Read(0x4001bc26d8?, {0x4000ed2000?, 0x4001bc26d8?, 0x1f2cc?}, 0xeac720?)
	github.com/pion/interceptor@v0.1.29/interceptor.go:91 +0x38
github.com/pion/webrtc/v3.(*RTPReceiver).readRTP(0x4001470bd0, {0x4000ed2000, 0x5b4, 0x5b4}, 0x4001849560)
	github.com/pion/webrtc/v3@v3.2.40/rtpreceiver.go:369 +0x11c
github.com/pion/webrtc/v3.(*TrackRemote).Read(0x4001849560, {0x4000ed2000, 0x5b4, 0x5b4})
	github.com/pion/webrtc/v3@v3.2.40/track_remote.go:139 +0x240
github.com/pion/webrtc/v3.(*TrackRemote).ReadRTP(0x4001849560)
	github.com/pion/webrtc/v3@v3.2.40/track_remote.go:177 +0x64
```

The main difference I notice is that we are receiving the track (onTrack event) and a few moments after we get an unhandled RTP error causing everything to halt:

```
trace [2024-07-18 10:31:59.405 +02:00] got new track: &{mu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:0} readerWait:{_:{} v:0}} id:31646962-5b22-4b42-9b1c-0e4dd0079edd streamID:fd0e4e8f-f667-4991-8842-0fe56f0df8fb payloadType:111 kind:1 ssrc:2433275910 rtxSsrc:0 codec:{RTPCodecCapability:{MimeType:audio/opus ClockRate:48000 Channels:2 SDPFmtpLine:minptime=10;useinbandfec=1 RTCPFeedback:[{Type:transport-cc Parameter:}]} PayloadType:111 statsID:} params:{HeaderExtensions:[{URI:urn:ietf:params:rtp-hdrext:ssrc-audio-level ID:1} {URI:http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01 ID:5}] Codecs:[{RTPCodecCapability:{MimeType:audio/opus ClockRate:48000 Channels:2 SDPFmtpLine:minptime=10;useinbandfec=1 RTCPFeedback:[{Type:transport-cc Parameter:}]} PayloadType:111 statsID:}]} rid: receiver:0xc0025854d0 peeked:[144 111 49 65 51 239 155 157 145 8 216 6 190 222 0 2 81 0 4 16 181 0 0 0 120 138 111 212 170 245 159 35 216 51 51 123 131 13 60 180 22 64 177 99 47 100 220 13 124 241 55 132 140 242 215 54 60 139 188 223 215 171 57 206 239 254 172 51 113 195 98 173 198 126 184 228 88 126 120 127 141 216 116 149 255 170 135 207 108 59 253 48 15 253 24 143 142 211 180] peekedAttributes:map[0:0xc002409770]} caller="rtc/logger.go:62" origin="webrtc/v3.(*PeerConnection).onTrack webrtc/v3@v3.2.40/peerconnection.go:466"
error [2024-07-18 10:31:59.746 +02:00] Incoming unhandled RTP ssrc(2433275910), OnTrack will not be fired. incoming SSRC failed Simulcast probing caller="rtc/logger.go:86" origin="webrtc/v3.(*PeerConnection).undeclaredRTPMediaProcessor.func1 webrtc/v3@v3.2.40/peerconnection.go:1679"
```

On previous (working) versions, we'd get the sporadic unhandled RTP error, but it would be followed by the OnTrack event firing.

/cc @paulwe @cnderrauber @Sean-Der

### PR DESCRIPTION
**Pull request by edaniels**
#### Description
This changes Close from being a "signaler" to a "broadcaster" of the notify condition. There's a small, but possible chance that between `Unlock` and `select` at the bottom of `Read` that we will have concurrent reads in the same position which means only once can receive a notify. If a `Close` happens in between this time, one or more reads will be blocked. One such case where this happen is for an srtp and srtcp reader.

In a simpler case, one read in the same position may miss a notify event during a Close. This affects any basic use of a *packetio.Buffer.

#### Reference issue
Fixes #298 and #299 (maybe)

I reproduced this with synchronization points at the critical point mentioned such that we start 2 reads, close before the select, and then continue the reads, at which point the test will time out. The new test, as such, is non-deterministic without the manual sync points.

### CODE REVIEW

File: packetio/buffer.go [hunk 1]
```diff
@@ -287,10 +287,7 @@ func (b *Buffer) Close() (err error) {
 	b.mutex.Unlock()
```
Comment (edaniels) [inline packetio/buffer.go:288]: this "section" is where the bad things happen

**Review by paulwe — APPROVED** [review]

**Comment by paulwe** [comment]
there was an assumption that concurrent reads would not happen so there may be other issues. if we read, write, read, close and the read, write, and read goroutines are all in the same gap between the critical section and channel op we could panic writing to a closed channel if close closes the channel before write sends.

**Comment by edaniels** [comment]
> there was an assumption that concurrent reads would not happen so there may be other issues. if we read, write, read, close and the read, write, and read goroutines are all in the same gap between the critical section and channel op we could panic writing to a closed channel if close closes the channel before write sends.

ah you're right on `write` being buggy now. I'll work on a more holistic fix for that.
